export type CategoryRow = {
  Category: string;
  Typology: string;
  Style: string;
  ClimateAdaptability: string;
  Terrain: string;
  SoilType: string;
  MaterialUsed: string;
  InteriorLayout: string;
  RoofType: string;
  Exterior: string;
  AdditionalFeatures: string;
  Sustainability: string;
};

const EMPTY = "-";

const FULL_ROWS: CategoryRow[] = [
  {
    Category: "Residential",
    Typology: "Residential- Apartment",
    Style: "Classical",
    ClimateAdaptability: "Hot & Dry",
    Terrain: "Flat",
    SoilType: "Loose",
    MaterialUsed: "Stone",
    InteriorLayout: "Open",
    RoofType: "Flat",
    Exterior: "Facade",
    AdditionalFeatures: "Balconies",
    Sustainability: "Passive Solar Design"
  },
  {
    Category: "Commercial",
    Typology: "Residential- Condominium",
    Style: "Gothic",
    ClimateAdaptability: "Hot & Humid",
    Terrain: "Sloping",
    SoilType: "Soft",
    MaterialUsed: "Brick",
    InteriorLayout: "Closed",
    RoofType: "Gable",
    Exterior: "Cladding",
    AdditionalFeatures: "Verandas",
    Sustainability: "Green Roofs"
  },
  {
    Category: "Industrial",
    Typology: "Residential- Single-Family House",
    Style: "Renaissance",
    ClimateAdaptability: "Cold & Dry",
    Terrain: "Hilly",
    SoilType: "Firm",
    MaterialUsed: "Concrete",
    InteriorLayout: "Linear",
    RoofType: "Hip",
    Exterior: "Siding",
    AdditionalFeatures: "Terraces",
    Sustainability: "Rainwater Harvesting"
  },
  {
    Category: "Recreational",
    Typology: "Residential- Duplex",
    Style: "Baroque",
    ClimateAdaptability: "Cold",
    Terrain: "Mountainous",
    SoilType: "Stiff",
    MaterialUsed: "Steel",
    InteriorLayout: "Centralized",
    RoofType: "Shed",
    Exterior: "Stucco",
    AdditionalFeatures: "Patios",
    Sustainability: "Greywater Recycling"
  },
  {
    Category: "Institutional",
    Typology: "Residential- Triplex",
    Style: "Neoclassical",
    ClimateAdaptability: "Temperate",
    Terrain: "Coastal",
    SoilType: "Dense",
    MaterialUsed: "Glass",
    InteriorLayout: "Radial",
    RoofType: "Mansard",
    Exterior: "Brickwork",
    AdditionalFeatures: "Decks",
    Sustainability: "Natural Ventilation"
  },
  {
    Category: "Agricultural",
    Typology: "Residential- Row House",
    Style: "Victorian",
    ClimateAdaptability: "Composite",
    Terrain: "Waterfront",
    SoilType: "Hard",
    MaterialUsed: "Wood",
    InteriorLayout: "Grid",
    RoofType: "Gambrel",
    Exterior: "Stone Veneer",
    AdditionalFeatures: "Pergolas",
    Sustainability: "Thermal Mass"
  },
  {
    Category: "Mixed-Use",
    Typology: "Residential- Bunglow",
    Style: "Beaux-Arts",
    ClimateAdaptability: "Tropical",
    Terrain: "Sandy",
    SoilType: "Rocky",
    MaterialUsed: "Bamboo",
    InteriorLayout: "Cluster",
    RoofType: "Butterfly",
    Exterior: "Glass Curtain Wall",
    AdditionalFeatures: "Atriums",
    Sustainability: "Daylighting"
  },
  {
    Category: "Infrastructural",
    Typology: "Residential- Cottage",
    Style: "Art Nouveau",
    ClimateAdaptability: "Tundra",
    Terrain: "Tropical",
    SoilType: "Clayey",
    MaterialUsed: "Aluminum",
    InteriorLayout: "Split-Level",
    RoofType: "Dome",
    Exterior: "Timber Exterior",
    AdditionalFeatures: "Courtyards",
    Sustainability: "Net-Zero Energy Design"
  },
  {
    Category: "Residential",
    Typology: "Residential- Villa",
    Style: "Art Deco",
    ClimateAdaptability: "Tropical Rainforest",
    Terrain: "Plateau",
    SoilType: "sandy clay",
    MaterialUsed: "Copper",
    InteriorLayout: "Loft",
    RoofType: "Pyramid",
    Exterior: "Metal Panels",
    AdditionalFeatures: "Bay Windows",
    Sustainability: "Low-Carbon Materials"
  },
  {
    Category: "Residential",
    Typology: "Residential- Mansion",
    Style: "Modernism",
    ClimateAdaptability: "Tropical Monsoon",
    Terrain: "Valley",
    SoilType: "silty clay",
    MaterialUsed: "Clay",
    InteriorLayout: "Courtyard",
    RoofType: "Curved",
    Exterior: "Green Walls",
    AdditionalFeatures: "Skylights",
    Sustainability: "Recycled Materials"
  },
  {
    Category: "Residential",
    Typology: "Residential- Studio Apartment",
    Style: "Bauhaus",
    ClimateAdaptability: "Tropical Savanna",
    Terrain: "Riverfront",
    SoilType: "Loamy",
    MaterialUsed: "Plaster & Stucco",
    InteriorLayout: "Studio",
    RoofType: "Green",
    Exterior: "Pergolas",
    AdditionalFeatures: "Chimneys",
    Sustainability: "Modular Construction"
  },
  {
    Category: "Residential",
    Typology: "Residential- Loft",
    Style: "International Style",
    ClimateAdaptability: "Hot Desert",
    Terrain: "Lakefront",
    SoilType: "sandy loam",
    MaterialUsed: "Adobe",
    InteriorLayout: "Staggered",
    RoofType: "Sawtooth",
    Exterior: "Awnings",
    AdditionalFeatures: "Columns",
    Sustainability: "Smart Glass"
  },
  {
    Category: "Residential",
    Typology: "Residential- Penthouse",
    Style: "Mid-Century Modern",
    ClimateAdaptability: "Cold Desert",
    Terrain: "Swamp",
    SoilType: "silty loam",
    MaterialUsed: "Rammed Earth",
    InteriorLayout: EMPTY,
    RoofType: "Thatch",
    Exterior: "Canopies",
    AdditionalFeatures: "Arches",
    Sustainability: "Solar Panels (Photovoltaics)"
  },
  {
    Category: "Residential",
    Typology: "Residential- Farmhouse",
    Style: "Brutalism",
    ClimateAdaptability: "Hot Semi-Arid",
    Terrain: "Floodplains",
    SoilType: "Silty",
    MaterialUsed: "Acrylic",
    InteriorLayout: EMPTY,
    RoofType: "Barrel Vault",
    Exterior: "Balconies",
    AdditionalFeatures: "Domes",
    Sustainability: "Wind Energy Integration"
  },
  {
    Category: "Residential",
    Typology: "Residential- Earth Shelter",
    Style: "Postmodernism",
    ClimateAdaptability: "Cold Semi-Arid",
    Terrain: "Cliff",
    SoilType: "sand",
    MaterialUsed: "Fiber-reinforced",
    InteriorLayout: EMPTY,
    RoofType: "Hip & Valley",
    Exterior: "Verandas",
    AdditionalFeatures: "Spires",
    Sustainability: "Geothermal Heating & Cooling"
  },
  {
    Category: "Commercial",
    Typology: "Commercial- Office Buildings",
    Style: "Deconstructivism",
    ClimateAdaptability: "Mediterranean",
    Terrain: "Marine",
    SoilType: "loamy sand",
    MaterialUsed: "CSEB (Compressed Stabilized Earth Blocks)",
    InteriorLayout: EMPTY,
    RoofType: "Truss Roof",
    Exterior: "Porches",
    AdditionalFeatures: "Staircases",
    Sustainability: "Biomimicry Design"
  },
  {
    Category: "Commercial",
    Typology: "Commercial- Retail Stores",
    Style: "Minimalism",
    ClimateAdaptability: "Continental",
    Terrain: EMPTY,
    SoilType: "Black Soil",
    MaterialUsed: "PVC",
    InteriorLayout: EMPTY,
    RoofType: EMPTY,
    Exterior: "Patios",
    AdditionalFeatures: "Escalators",
    Sustainability: "BREEAM Standards"
  },
  {
    Category: "Commercial",
    Typology: "Commercial- Shopping Malls",
    Style: "Neo-Futurism",
    ClimateAdaptability: EMPTY,
    Terrain: EMPTY,
    SoilType: "Red Soil",
    MaterialUsed: "Translucent Concrete",
    InteriorLayout: EMPTY,
    RoofType: EMPTY,
    Exterior: "Decks",
    AdditionalFeatures: "Elevators",
    Sustainability: "Circular Economy Design"
  },
  {
    Category: "Commercial",
    Typology: "Commercial- Restaurants",
    Style: "Bohemian",
    ClimateAdaptability: EMPTY,
    Terrain: EMPTY,
    SoilType: "Alluvial Soil",
    MaterialUsed: "Hydroceramics",
    InteriorLayout: EMPTY,
    RoofType: EMPTY,
    Exterior: "Driveways",
    AdditionalFeatures: "Ramps",
    Sustainability: "Adaptive Reuse"
  },
  {
    Category: "Commercial",
    Typology: "Commercial- Cafes",
    Style: "Industrial",
    ClimateAdaptability: EMPTY,
    Terrain: EMPTY,
    SoilType: "Yellow Soil",
    MaterialUsed: EMPTY,
    InteriorLayout: EMPTY,
    RoofType: EMPTY,
    Exterior: "Fences",
    AdditionalFeatures: "Fireplaces",
    Sustainability: "Carbon-Neutral Construction"
  },
  {
    Category: "Commercial",
    Typology: "Commercial- Hotels",
    Style: "Eco-architecture",
    ClimateAdaptability: EMPTY,
    Terrain: EMPTY,
    SoilType: "Light Grey Soil",
    MaterialUsed: EMPTY,
    InteriorLayout: EMPTY,
    RoofType: EMPTY,
    Exterior: "Eaves",
    AdditionalFeatures: "Gates",
    Sustainability: "Green Cover Preservation"
  },
  {
    Category: "Commercial",
    Typology: "Commercial- Hostels",
    Style: "Japananese",
    ClimateAdaptability: EMPTY,
    Terrain: EMPTY,
    SoilType: EMPTY,
    MaterialUsed: EMPTY,
    InteriorLayout: EMPTY,
    RoofType: EMPTY,
    Exterior: EMPTY,
    AdditionalFeatures: "Water Features (Pond)",
    Sustainability: EMPTY
  },
  {
    Category: "Commercial",
    Typology: "Commercial- Resorts",
    Style: "Parametric",
    ClimateAdaptability: EMPTY,
    Terrain: EMPTY,
    SoilType: EMPTY,
    MaterialUsed: EMPTY,
    InteriorLayout: EMPTY,
    RoofType: EMPTY,
    Exterior: EMPTY,
    AdditionalFeatures: "Water Features (Fountain)",
    Sustainability: EMPTY
  },
  {
    Category: "Commercial",
    Typology: "Commercial- Motels",
    Style: "Scandinavian",
    ClimateAdaptability: EMPTY,
    Terrain: EMPTY,
    SoilType: EMPTY,
    MaterialUsed: EMPTY,
    InteriorLayout: EMPTY,
    RoofType: EMPTY,
    Exterior: EMPTY,
    AdditionalFeatures: EMPTY,
    Sustainability: EMPTY
  },
  {
    Category: "Commercial",
    Typology: "Commercial- Theaters",
    Style: "Fachwerk/ Half-Timbered",
    ClimateAdaptability: EMPTY,
    Terrain: EMPTY,
    SoilType: EMPTY,
    MaterialUsed: EMPTY,
    InteriorLayout: EMPTY,
    RoofType: EMPTY,
    Exterior: EMPTY,
    AdditionalFeatures: EMPTY,
    Sustainability: EMPTY
  },
  {
    Category: "Commercial",
    Typology: "Commercial- Convention Centers",
    Style: "Greek Revival",
    ClimateAdaptability: EMPTY,
    Terrain: EMPTY,
    SoilType: EMPTY,
    MaterialUsed: EMPTY,
    InteriorLayout: EMPTY,
    RoofType: EMPTY,
    Exterior: EMPTY,
    AdditionalFeatures: EMPTY,
    Sustainability: EMPTY
  },
  {
    Category: "Commercial",
    Typology: "Commercial- Exhibition Halls",
    Style: "Contemporary",
    ClimateAdaptability: EMPTY,
    Terrain: EMPTY,
    SoilType: EMPTY,
    MaterialUsed: EMPTY,
    InteriorLayout: EMPTY,
    RoofType: EMPTY,
    Exterior: EMPTY,
    AdditionalFeatures: EMPTY,
    Sustainability: EMPTY
  },
  {
    Category: "Commercial",
    Typology: "Commercial- Clinics",
    Style: "Chinese",
    ClimateAdaptability: EMPTY,
    Terrain: EMPTY,
    SoilType: EMPTY,
    MaterialUsed: EMPTY,
    InteriorLayout: EMPTY,
    RoofType: EMPTY,
    Exterior: EMPTY,
    AdditionalFeatures: EMPTY,
    Sustainability: EMPTY
  },
  {
    Category: "Commercial",
    Typology: "Commercial- Banks",
    Style: "Romanesque",
    ClimateAdaptability: EMPTY,
    Terrain: EMPTY,
    SoilType: EMPTY,
    MaterialUsed: EMPTY,
    InteriorLayout: EMPTY,
    RoofType: EMPTY,
    Exterior: EMPTY,
    AdditionalFeatures: EMPTY,
    Sustainability: EMPTY
  },
  {
    Category: "Commercial",
    Typology: "Commercial- Warehouses",
    Style: "Queenslander",
    ClimateAdaptability: EMPTY,
    Terrain: EMPTY,
    SoilType: EMPTY,
    MaterialUsed: EMPTY,
    InteriorLayout: EMPTY,
    RoofType: EMPTY,
    Exterior: EMPTY,
    AdditionalFeatures: EMPTY,
    Sustainability: EMPTY
  },
  {
    Category: "Commercial",
    Typology: "Commercial- Showrooms",
    Style: "Federation",
    ClimateAdaptability: EMPTY,
    Terrain: EMPTY,
    SoilType: EMPTY,
    MaterialUsed: EMPTY,
    InteriorLayout: EMPTY,
    RoofType: EMPTY,
    Exterior: EMPTY,
    AdditionalFeatures: EMPTY,
    Sustainability: EMPTY
  }
];

const EXTRA_TYPOLOGIES = [
  "Commercial- Supermarkets",
  "Commercial- Mixed-Use Buildings",
  "Industrial- Factories",
  "Industrial- Manufacturing Plants",
  "Industrial- Warehouses",
  "Industrial- Distribution Centers",
  "Industrial- Power Plants",
  "Industrial- Refineries",
  "Industrial- Steel Mills",
  "Industrial- Chemical Plants",
  "Industrial- Food Processing Plants",
  "Industrial- Textile Mills",
  "Industrial- Breweries",
  "Industrial- Shipyards",
  "Industrial- Mining Facilities",
  "Industrial- Industrial Parks",
  "Agricultural- Barns",
  "Agricultural- Silos",
  "Agricultural- Greenhouses",
  "Agricultural- Farmhouses",
  "Agricultural- Storage Sheds",
  "Agricultural- Poultry Houses",
  "Agricultural- Cattle Sheds",
  "Agricultural- Piggeries",
  "Agricultural- Sheep Pens",
  "Agricultural- Stables",
  "Agricultural- Irrigation Structures",
  "Agricultural- Fencing",
  "Agricultural- Fish Farms",
  "Agricultural- Crop Processing Units",
  "Agricultural- Dairy Farms",
  "Recreational- Parks",
  "Recreational- Playgrounds",
  "Recreational- Stadiums",
  "Recreational- Sports Complexes",
  "Recreational- Gyms",
  "Recreational- Swimming Pools",
  "Recreational- Golf Courses",
  "Recreational- Resorts",
  "Recreational- Amusement Parks",
  "Recreational- Zoos",
  "Recreational- Aquariums",
  "Recreational- Museums",
  "Recreational- Art Galleries",
  "Recreational- Theaters",
  "Recreational- Cinemas",
  "Recreational- Community Centers",
  "Recreational- Clubs",
  "Recreational- Spas",
  "Recreational- Gaming Arcades",
  "Institutional- Schools",
  "Institutional- Colleges",
  "Institutional- Universities",
  "Institutional- Libraries",
  "Institutional- Research Institutes",
  "Institutional- Museums",
  "Institutional- Courthouses",
  "Institutional- Police Stations",
  "Institutional- Fire Stations",
  "Institutional- Post Officies",
  "Instituitonal- City Halls",
  "Institutional- Government Offices",
  "Institutional-Parliament",
  "Institutional- Embassies",
  "Institutional- Military Bases",
  "Institutional- Cultural Centers",
  "Institutional- Hospitals",
  "Institutional- Community Centers",
  "Mixed Use- Residential + Commercial",
  "Mised Use- Residential + Office",
  "Mixed Use- Residential + Retail",
  "Mixed Use- Office + Retail",
  "Mixed Use- Hotel + Residential",
  "Mixed Use- Hotel + Retail",
  "Mixed Use- Transit-Oriented Developments",
  "Mixed Use- Live-Work Units",
  "Mixed Use- Mall + Office + Residential",
  "Mixed Use- Smart Cities",
  "Infrastructural- Highways",
  "Infrastructural- Airports",
  "Infrastructural- Seaports",
  "Infrastructural- Bus Terminals",
  "Infrastructural- Metro",
  "Infrastructural- Dams",
  "Infrastructural- Canals",
  "Infrastructural- Irrigation Systems",
  "Infrastructural- Water Supply Systems",
  "Infrastructural- Sewage Systems",
  "Infrastructural- Power Plants",
  "Infrastructural- Transmission Lines",
  "Infrastructural- Telecommunication Towers",
  "Infrastructural- Pipelines",
  "Infrastructural- Parking Structures"
];

function rowFromTypology(value: string): CategoryRow {
  const parts = value.split("-");
  const category = (parts[0] || "Unknown").trim();
  return {
    Category: category,
    Typology: value.trim(),
    Style: EMPTY,
    ClimateAdaptability: EMPTY,
    Terrain: EMPTY,
    SoilType: EMPTY,
    MaterialUsed: EMPTY,
    InteriorLayout: EMPTY,
    RoofType: EMPTY,
    Exterior: EMPTY,
    AdditionalFeatures: EMPTY,
    Sustainability: EMPTY
  };
}

export const CATEGORY_ROWS: CategoryRow[] = [...FULL_ROWS, ...EXTRA_TYPOLOGIES.map(rowFromTypology)];
